{{ $component := "troubleshoot" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.fullname" . }}-preflight
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "troubleshoot.preflights" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise.fullname" . }}-support-bundle
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |- {{- include "troubleshoot.supportBundle" . | nindent 4 }}
